import { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType, Footer, PageNumber, TextRun } from 'docx'
import ExcelJS from 'exceljs'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { Project, budgetAmount, chapterTemplate, documentKinds, DocumentKind, validateProject, projectStatus } from './proposal-model'

const money = (value: number) => `${value.toLocaleString('bs-BA', { minimumFractionDigits: 2 })} KM`
const heading = (text: string) => new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 220, after: 100 } })
const cell = (text: string, bold = false) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text, bold })] })] })

function projectBody(project: Project) {
  return [heading(project.program.title), new Paragraph(project.program.need), heading('1. O podnosiocu prijave'), new Paragraph(`${project.applicant.name.value}\n${project.applicant.address.value}\n${project.applicant.contact.value}`), ...chapterTemplate.slice(1).map((chapter, index) => heading(`${index + 2}. ${chapter}`)), new Paragraph(project.program.generalGoal), heading('Plan aktivnosti'), new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [new TableRow({ children: ['Br.', 'Aktivnost', 'Period', 'Rezultat'].map(value => cell(value, true)) }), ...project.activities.map(activity => new TableRow({ children: [String(activity.no), activity.activity, activity.period, activity.result].map(value => cell(value)) }))] }), heading('Usklađenost sa Javnim oglasom'), new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [new TableRow({ children: ['Tačka', 'Zahtjev', 'Ispunjenje'].map(value => cell(value, true)) }), ...project.callCompliance.map(item => new TableRow({ children: [item.callPoint, item.requirement, item.fulfillment].map(value => cell(value)) }))] })]
}

export async function generateDocx(project: Project, kind: DocumentKind): Promise<Buffer> {
  const title = documentKinds.find(item => item.kind === kind)?.label ?? 'Projektni dokument'
  const children = kind === 'proposal' ? projectBody(project) : [heading(title), new Paragraph(`KVS „S.C.U.B.A.“ Sarajevo · ${project.program.title}`), new Paragraph(kind === 'letter' ? `Poštovani, Klub vodenih sportova „S.C.U.B.A.“ Sarajevo prijavljuje projekat ${project.program.title} i traži podršku u iznosu ${money(project.program.requestedFromDonor)}.` : kind === 'statements' ? project.statements.map(statement => `• ${statement}`).join('\n') : project.documentation.map(item => `${item.name} · ${item.callPoint} · ${item.note}`).join('\n'))]
  const doc = new Document({ sections: [{ properties: {}, footers: { default: new Footer({ children: [new Paragraph({ children: [new TextRun('KVS „S.C.U.B.A.“ Sarajevo · '), PageNumber.CURRENT] })] }) }, children }] })
  return Buffer.from(await Packer.toBuffer(doc))
}

export async function generateBudgetXlsx(project: Project): Promise<Buffer> { const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet('Budžet'); sheet.columns = [{ header: 'Stavka', key: 'description', width: 48 }, { header: 'Jedinica', key: 'unit', width: 16 }, { header: 'Količina', key: 'quantity', width: 12 }, { header: 'Jedinična cijena', key: 'unitPrice', width: 18 }, { header: 'Izvor', key: 'source', width: 16 }, { header: 'Ukupno', key: 'total', width: 18 }]; sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0E5966' } }; project.budget.forEach((line, index) => { const row = sheet.addRow({ description: line.description, unit: line.unit, quantity: line.quantity, unitPrice: line.unitPrice, source: line.source }); row.getCell('total').value = { formula: `C${index + 2}*D${index + 2}` }; }); const totalRow = sheet.addRow({ description: 'UKUPNO' }); totalRow.getCell('total').value = { formula: `SUM(F2:F${project.budget.length + 1})` }; totalRow.font = { bold: true }; sheet.addRow({ description: 'Kontrolna ćelija (mora biti 0,00)', total: { formula: `F${project.budget.length + 2}-${project.program.totalBudget}` } }); return Buffer.from(await workbook.xlsx.writeBuffer()) }

export async function generatePdf(project: Project, kind: DocumentKind): Promise<Buffer> { const pdf = await PDFDocument.create(); const page = pdf.addPage([595, 842]); const font = await pdf.embedFont(StandardFonts.Helvetica); page.drawText(documentKinds.find(item => item.kind === kind)?.label ?? 'Dokument', { x: 48, y: 790, size: 20, font, color: rgb(0.05, 0.35, 0.4) }); page.drawText(project.program.title, { x: 48, y: 755, size: 11, font, maxWidth: 500 }); page.drawText(`Traženi iznos: ${money(project.program.requestedFromDonor)}`, { x: 48, y: 720, size: 11, font }); page.drawText('Ovaj PDF je generisan iz validiranog strukturiranog modela podataka.', { x: 48, y: 660, size: 10, font }); return Buffer.from(await pdf.save()) }

export async function generatePackage(project: Project) { const validation = validateProject(project); const status = projectStatus(project); const files = await Promise.all(documentKinds.map(async ({ kind, label }) => ({ name: `${kind}.docx`, label, mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', data: (kind === 'budget' ? await generateBudgetXlsx(project) : await generateDocx(project, kind)).toString('base64'), preview: (await generatePdf(project, kind)).toString('base64') }))); return { status, validation, files } }
